module.exports.userController = require('./user.controller')
module.exports.categoryController = require('./category.controller')
module.exports.articleController = require('./article.controller')
module.exports.likeController = require('./like.controller')
module.exports.commentController = require('./comment.controller')
module.exports.followerController = require('./follower.controller')
